### ISSUE TITLE
Chunk Memory Optimization

### ISSUE THREAD

**Issue by Sigurd-Pettersen** [mattiastofte/minecraft-clone#11]
Considering each number represents a block type and since you probably wont go over 256 blocks you could use the primitive data type: byte. This will avoid using 4 bytes with an int type for each positional value used to represent a block in the chunk and instead use 1 byte which still has a range of 256 possible representations. Possibly increasing speed and increasing memory efficiency

**Comment by mattiastofte** [comment]
I agree! Although the biggest issue right now is that each voxel has its own MeshView and mesh object. I think it would be beneficial to put all the mesh points in one MeshView for each chunk, but then you loose methods to modify/detect collisions for each seperate voxel (they will only work on a chunk basis)

**Comment by Sigurd-Pettersen** [comment]
When it comes to collisions the most efficient way for a 3d game is to use a tree of bounding boxes for models consisting of a large number of vertices. However considering this is a Minecraft clone consisting of perfectly squared boxes you could get away with creating a bounding box for each dynamic object (player, enemies...) and check for each block their bounding box covers in the Chunks.data array to detect collisions very efficiently instead of using the voxel. This also opens the opportunity for different behavior when colliding with each block type. This is also why the Chunks.data could hold byte values instead of int values to avoid multiplying the number of bytes it takes up in memory by 4 and increase generation and speed efficiency while not affecting it's ability to detect collisions.
